### ISSUE TITLE
How about a better class name?

### ISSUE THREAD

**Issue by Egis-Kevin** [Zeets-code/parseHTML-stdout-JSON#1]
https://github.com/Zeets-code/parseHTML-stdout-JSON/blob/c96631107777fa028a52d57f54f274067433b613/parseHTML/src/parseHTML/parseHTML.java#L12

**Comment by Zeets-code** [comment]
How about ParseHtml?

**Comment by Egis-Kevin** [comment]
That is better!

> How about ParseHtml?
