### ISSUE TITLE
Why are we skipping over Monitoring?

### ISSUE THREAD

**Issue by Egis-Kevin** [Zeets-code/parseHTML-stdout-JSON#2]
https://github.com/Zeets-code/parseHTML-stdout-JSON/blob/c96631107777fa028a52d57f54f274067433b613/parseHTML/src/parseHTML/parseHTML.java#L29

**Comment by Zeets-code** [comment]
I assumed you wanted to because you didn't list that technology in the email, will rectify this.

**Comment by Egis-Kevin** [comment]
No please do not. This is correct 🥇
