### ISSUE TITLE
General Issues

### ISSUE THREAD

**Issue by Egis-Kevin** [Zeets-code/parseHTML-stdout-JSON#4]
1. Code formatting
2. Variable names should be short and descriptive `camelCase`
3. Class names should be short and descriptive `CamelCase`

**Comment by Zeets-code** [comment]
I will fix the variable and class names, apologies. Can you elaborate further on the formatting issue?

**Comment by Egis-Kevin** [comment]
> I will fix the variable and class names, apologies. Can you elaborate further on the formatting issue?

most IDE's have code formatting built in, which formats your code in a very nice readable way. correctly spaces and tabs it

**Comment by Zeets-code** [comment]
Ah I see will fix that too!

**Comment by Egis-Kevin** [comment]
looks much better, will close
